// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// phi
double phi(double x);
RcppExport SEXP _GPOreg_phi(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(phi(x));
    return rcpp_result_gen;
END_RCPP
}
// kernelC2
double kernelC2(NumericVector xb, NumericVector pihat, NumericVector wi, double Cn);
RcppExport SEXP _GPOreg_kernelC2(SEXP xbSEXP, SEXP pihatSEXP, SEXP wiSEXP, SEXP CnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xb(xbSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pihat(pihatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wi(wiSEXP);
    Rcpp::traits::input_parameter< double >::type Cn(CnSEXP);
    rcpp_result_gen = Rcpp::wrap(kernelC2(xb, pihat, wi, Cn));
    return rcpp_result_gen;
END_RCPP
}
// myrank
NumericVector myrank(NumericVector x, NumericVector wi);
RcppExport SEXP _GPOreg_myrank(SEXP xSEXP, SEXP wiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wi(wiSEXP);
    rcpp_result_gen = Rcpp::wrap(myrank(x, wi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GPOreg_phi", (DL_FUNC) &_GPOreg_phi, 1},
    {"_GPOreg_kernelC2", (DL_FUNC) &_GPOreg_kernelC2, 4},
    {"_GPOreg_myrank", (DL_FUNC) &_GPOreg_myrank, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_GPOreg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
