# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

phi <- function(x) {
    .Call(`_GPOreg_phi`, x)
}

kernelC2 <- function(xb, pihat, wi, Cn) {
    .Call(`_GPOreg_kernelC2`, xb, pihat, wi, Cn)
}

myrank <- function(x, wi) {
    .Call(`_GPOreg_myrank`, x, wi)
}

